
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vaibhav
 */
public class AdminLogin extends javax.swing.JFrame {
    static Database database;
    static DB_URL dbUrl;
    static PreparedStatement ps;
    static ResultSet rs;
    static String sql=null;
    static Login L;
    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {
        dbUrl=new DB_URL();
        database=new Database(dbUrl.URL);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLogout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxEnabled = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxDisabled = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxFrozen = new javax.swing.JComboBox<>();
        jButtonDeactivate_E = new javax.swing.JButton();
        jButtonFreeze_E = new javax.swing.JButton();
        jButtonEnable_D = new javax.swing.JButton();
        jButtonFreeze_D = new javax.swing.JButton();
        jButtonEnable_F = new javax.swing.JButton();
        jButtonDeactivate_F = new javax.swing.JButton();
        jLabelEnabled = new javax.swing.JLabel();
        jLabelDeactivate = new javax.swing.JLabel();
        jLabelFreeze = new javax.swing.JLabel();
        jButtonRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[Administrator] Logged in");

        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jLabel1.setText("Active Accounts:");

        jComboBoxEnabled.setModel(new javax.swing.DefaultComboBoxModel<>(returnAccountStatus("e")));
        jComboBoxEnabled.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEnabledItemStateChanged(evt);
            }
        });

        jLabel2.setText("Deactivated Accounts: ");

        jComboBoxDisabled.setModel(new javax.swing.DefaultComboBoxModel<>(returnAccountStatus("d")));

        jLabel3.setText("Frozen Accounts: ");

        jComboBoxFrozen.setModel(new javax.swing.DefaultComboBoxModel<>(returnAccountStatus("f")));

        jButtonDeactivate_E.setText("Deactivate");
        jButtonDeactivate_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeactivate_EActionPerformed(evt);
            }
        });

        jButtonFreeze_E.setText("Freeze");
        jButtonFreeze_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFreeze_EActionPerformed(evt);
            }
        });

        jButtonEnable_D.setText("Activate");
        jButtonEnable_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnable_DActionPerformed(evt);
            }
        });

        jButtonFreeze_D.setText("Freeze");
        jButtonFreeze_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFreeze_DActionPerformed(evt);
            }
        });

        jButtonEnable_F.setText("Activate");
        jButtonEnable_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnable_FActionPerformed(evt);
            }
        });

        jButtonDeactivate_F.setText("Deactivate");
        jButtonDeactivate_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeactivate_FActionPerformed(evt);
            }
        });

        jButtonRefresh.setText("Refresh Data");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1)
                                .addGap(26, 26, 26)
                                .addComponent(jComboBoxEnabled, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelEnabled, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jButtonLogout)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonFreeze_E)
                                    .addComponent(jButtonDeactivate_E)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRefresh)
                                .addGap(22, 22, 22))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxDisabled, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelDeactivate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonFreeze_D)
                                    .addComponent(jButtonEnable_D)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(26, 26, 26)
                                        .addComponent(jComboBoxFrozen, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelFreeze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonDeactivate_F)
                                    .addComponent(jButtonEnable_F))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogout)
                    .addComponent(jButtonRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxEnabled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeactivate_E))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFreeze_E)
                    .addComponent(jLabelEnabled))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxDisabled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnable_D))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFreeze_D)
                    .addComponent(jLabelDeactivate))
                .addGap(24, 24, 24)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxFrozen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnable_F))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDeactivate_F)
                    .addComponent(jLabelFreeze))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeactivate_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeactivate_EActionPerformed
        // TODO add your handling code here:
        String uname=(String) jComboBoxEnabled.getSelectedItem();
        sql="update account set temp=? where user=?";
        try {
            ps=database.conn.prepareStatement(sql);
            ps.setString(1, "d");
            ps.setString(2, uname);
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(AdminLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        refreshComboBox(jComboBoxEnabled,"e");
        refreshComboBox(jComboBoxDisabled,"d");
        refreshComboBox(jComboBoxFrozen, "f");
    }//GEN-LAST:event_jButtonDeactivate_EActionPerformed

    private void jButtonFreeze_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFreeze_EActionPerformed
        // TODO add your handling code here:
        String uname=(String) jComboBoxEnabled.getSelectedItem();
        sql="update account set temp=? where user=?";
        try {
            ps=database.conn.prepareStatement(sql);
            ps.setString(1, "f");
            ps.setString(2, uname);
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(AdminLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        refreshComboBox(jComboBoxEnabled,"e");
        refreshComboBox(jComboBoxDisabled,"d");
        refreshComboBox(jComboBoxFrozen, "f");
    }//GEN-LAST:event_jButtonFreeze_EActionPerformed

    private void jButtonEnable_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnable_DActionPerformed
        // TODO add your handling code here:
        String uname=(String) jComboBoxDisabled.getSelectedItem();
        sql="update account set temp=? where user=?";
        try {
            ps=database.conn.prepareStatement(sql);
            ps.setString(1, "e");
            ps.setString(2, uname);
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(AdminLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        refreshComboBox(jComboBoxEnabled,"e");
        refreshComboBox(jComboBoxDisabled,"d");
        refreshComboBox(jComboBoxFrozen, "f");
    }//GEN-LAST:event_jButtonEnable_DActionPerformed

    private void jButtonFreeze_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFreeze_DActionPerformed
        // TODO add your handling code here:
        String uname=(String) jComboBoxDisabled.getSelectedItem();
        sql="update account set temp=? where user=?";
        try {
            ps=database.conn.prepareStatement(sql);
            ps.setString(1, "f");
            ps.setString(2, uname);
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(AdminLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
       refreshComboBox(jComboBoxEnabled,"e");
        refreshComboBox(jComboBoxDisabled,"d");
        refreshComboBox(jComboBoxFrozen, "f");
    }//GEN-LAST:event_jButtonFreeze_DActionPerformed

    private void jButtonEnable_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnable_FActionPerformed
        // TODO add your handling code here:
        String uname=(String) jComboBoxFrozen.getSelectedItem();
        sql="update account set temp=? where user=?";
        try {
            ps=database.conn.prepareStatement(sql);
            ps.setString(1, "e");
            ps.setString(2, uname);
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(AdminLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        refreshComboBox(jComboBoxEnabled,"e");
        refreshComboBox(jComboBoxDisabled,"d");
        refreshComboBox(jComboBoxFrozen, "f");
    }//GEN-LAST:event_jButtonEnable_FActionPerformed

    private void jButtonDeactivate_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeactivate_FActionPerformed
        // TODO add your handling code here:
        String uname=(String) jComboBoxFrozen.getSelectedItem();
        sql="update account set temp=? where user=?";
        try {
            ps=database.conn.prepareStatement(sql);
            ps.setString(1, "d");
            ps.setString(2, uname);
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(AdminLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        refreshComboBox(jComboBoxEnabled,"e");
        refreshComboBox(jComboBoxDisabled,"d");
        refreshComboBox(jComboBoxFrozen, "f");
    }//GEN-LAST:event_jButtonDeactivate_FActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        System.out.println("Logging out: Admin");
        L=new Login();
        L.setVisible(true);
        AdminLogin.this.dispose();
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jComboBoxEnabledItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEnabledItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEnabledItemStateChanged

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        // TODO add your handling code here:
        refreshComboBox(jComboBoxEnabled,"e");
        refreshComboBox(jComboBoxDisabled,"d");
        refreshComboBox(jComboBoxFrozen, "f");
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }
    
    static String[] returnAccountStatus(String id) {
        sql="select user from account where temp=?";
        System.out.println(id);
        ArrayList<String> names=new ArrayList<>();
        try {
            ps=database.conn.prepareStatement(sql);
            ps.setString(1,id);
            rs=ps.executeQuery();
            while(rs.next()) {
                names.add(rs.getString("user"));
            }
            if(!names.isEmpty()) {
                String nameArr[]=new String[names.size()];
                nameArr=names.toArray(nameArr);
                return nameArr;
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminLogin.class.getName()).log(Level.SEVERE, null, ex);
            return new String[] {"SQLException"};
        }
        return new String[] {"No accounts enabled"};
    }
    
    static void refreshComboBox(JComboBox<String> jcb,String id) {
        jcb.setModel(new javax.swing.DefaultComboBoxModel<>(returnAccountStatus(id)));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeactivate_E;
    private javax.swing.JButton jButtonDeactivate_F;
    private javax.swing.JButton jButtonEnable_D;
    private javax.swing.JButton jButtonEnable_F;
    private javax.swing.JButton jButtonFreeze_D;
    private javax.swing.JButton jButtonFreeze_E;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JComboBox<String> jComboBoxDisabled;
    private javax.swing.JComboBox<String> jComboBoxEnabled;
    private javax.swing.JComboBox<String> jComboBoxFrozen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDeactivate;
    private javax.swing.JLabel jLabelEnabled;
    private javax.swing.JLabel jLabelFreeze;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
